// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"github.com/chand19-af/digitels-template/app/controllers"
	"github.com/chand19-af/digitels-template/app/repositories"
	"github.com/chand19-af/digitels-template/app/services"
	"github.com/chand19-af/digitels-template/platform/database"
	"github.com/google/wire"
)

// Injectors from app_service_provider.go:

func InitializedServer() *controllers.HotelControllerImp {
	hotelRepositoryImpl := repositories.NewHotelRepository()
	db := database.GormMysqlConnection()
	hotelServiceImpl := services.NewHotelService(hotelRepositoryImpl, db)
	hotelControllerImp := controllers.NewHotelController(hotelServiceImpl)
	return hotelControllerImp
}

// app_service_provider.go:

var hotelSet = wire.NewSet(repositories.NewHotelRepository, wire.Bind(new(repositories.HotelRepository), new(*repositories.HotelRepositoryImpl)), services.NewHotelService, wire.Bind(new(services.HotelService), new(*services.HotelServiceImpl)), controllers.NewHotelController, wire.Bind(new(controllers.HotelControlller), new(*controllers.HotelControllerImp)))
